### ISSUE TITLE
αὐξάνω is not lemma of : προσαυξάνω.

### ISSUE THREAD

**Issue by nouveautestament** [PerseusDL/Perseus5#30]
![image](https://user-images.githubusercontent.com/84104408/169464960-ca88192b-5257-4c0a-97cc-c7be70eafaa9.png)

**Comment by lcerrato** [comment]
@nouveautestament 
Thank you for the report.
I will move this issue to the morpheus repository where there are two open issues for Greek and Latin respectively for errors in the morphological data. This repo is not active or under development.

https://github.com/PerseusDL/morpheus/issues

https://github.com/PerseusDL/morpheus/issues/20
https://github.com/PerseusDL/morpheus/issues/21
